"use client"

import jsPDF from "jspdf"
import "jspdf-autotable"

declare module "jspdf" {
  interface jsPDF {
    autoTable: (options: any) => jsPDF
  }
}

export interface StockReportData {
  products: Array<{
    product_code: string
    name: string
    sku: string
    category: string
    current_stock: number
    min_stock_level: number
    price: number
  }>
  reportDate: string
  reportId: string
}

export function generateStockReportPDF(data: StockReportData) {
  const doc = new jsPDF()

  // Header
  doc.setFontSize(20)
  doc.setTextColor(37, 99, 235) // Blue color
  doc.text("SmartStock", 20, 20)

  doc.setFontSize(16)
  doc.setTextColor(0, 0, 0)
  doc.text("Stock Inventory Report", 20, 35)

  // Report details
  doc.setFontSize(10)
  doc.text(`Report ID: ${data.reportId}`, 20, 50)
  doc.text(`Generated: ${data.reportDate}`, 20, 60)
  doc.text(`Total Products: ${data.products.length}`, 20, 70)

  // Low stock warning
  const lowStockCount = data.products.filter((p) => p.current_stock <= p.min_stock_level).length
  if (lowStockCount > 0) {
    doc.setTextColor(255, 0, 0)
    doc.text(`⚠️ Low Stock Alert: ${lowStockCount} products need restocking`, 20, 80)
    doc.setTextColor(0, 0, 0)
  }

  // Table data
  const tableData = data.products.map((product) => [
    product.product_code,
    product.name,
    product.sku,
    product.category,
    product.current_stock.toString(),
    product.min_stock_level.toString(),
    `₹${product.price.toFixed(2)}`,
    product.current_stock <= product.min_stock_level ? "⚠️ Low" : "✅ OK",
  ])

  // Generate table
  doc.autoTable({
    head: [["Code", "Product Name", "SKU", "Category", "Stock", "Min Level", "Price", "Status"]],
    body: tableData,
    startY: 90,
    styles: {
      fontSize: 8,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: [37, 99, 235],
      textColor: 255,
      fontStyle: "bold",
    },
    columnStyles: {
      0: { cellWidth: 20 },
      1: { cellWidth: 35 },
      2: { cellWidth: 25 },
      3: { cellWidth: 20 },
      4: { cellWidth: 15 },
      5: { cellWidth: 15 },
      6: { cellWidth: 20 },
      7: { cellWidth: 20 },
    },
    didParseCell: (data) => {
      if (data.column.index === 7 && data.cell.text[0].includes("Low")) {
        data.cell.styles.textColor = [255, 0, 0]
        data.cell.styles.fontStyle = "bold"
      }
    },
  })

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(128, 128, 128)
    doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 30, doc.internal.pageSize.height - 10)
    doc.text("Generated by SmartStock Inventory Management System", 20, doc.internal.pageSize.height - 10)
  }

  // Save the PDF
  doc.save(`SmartStock_Inventory_Report_${data.reportId}.pdf`)
}

export function generateProductDetailPDF(product: any) {
  const doc = new jsPDF()

  // Header
  doc.setFontSize(20)
  doc.setTextColor(37, 99, 235)
  doc.text("SmartStock", 20, 20)

  doc.setFontSize(16)
  doc.setTextColor(0, 0, 0)
  doc.text("Product Detail Report", 20, 35)

  // Product details
  doc.setFontSize(12)
  doc.text(`Product Code: ${product.product_code}`, 20, 55)
  doc.text(`Product Name: ${product.name}`, 20, 70)
  doc.text(`SKU: ${product.sku}`, 20, 85)
  doc.text(`Category: ${product.category}`, 20, 100)
  doc.text(`Price: ₹${product.price.toFixed(2)}`, 20, 115)
  doc.text(`Current Stock: ${product.current_stock}`, 20, 130)
  doc.text(`Minimum Level: ${product.min_stock_level}`, 20, 145)

  if (product.description) {
    doc.text(`Description: ${product.description}`, 20, 160)
  }

  // Status
  const status = product.current_stock <= product.min_stock_level ? "LOW STOCK - REORDER REQUIRED" : "STOCK OK"
  const statusColor = product.current_stock <= product.min_stock_level ? [255, 0, 0] : [0, 128, 0]

  doc.setTextColor(...statusColor)
  doc.setFontSize(14)
  doc.text(`Status: ${status}`, 20, 180)

  // QR Code placeholder (you can add actual QR code generation)
  doc.setTextColor(0, 0, 0)
  doc.setFontSize(10)
  doc.rect(20, 200, 50, 50)
  doc.text("QR Code", 35, 230)
  doc.text(product.product_code, 30, 240)

  // Footer
  doc.setFontSize(8)
  doc.setTextColor(128, 128, 128)
  doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 280)
  doc.text("SmartStock Inventory Management System", 20, 290)

  doc.save(`SmartStock_Product_${product.product_code}.pdf`)
}
